import type { PermissionScope } from "@prisma/client";

import { SYSTEM_PERMISSION_DEFINITIONS } from "../../src/shared/permissions/definitions";

export const SYSTEM_PERMISSIONS = SYSTEM_PERMISSION_DEFINITIONS.map(
  ({ module, resource, action, key, description }) => ({
    module,
    resource,
    action,
    key,
    description,
  }),
);

export type SystemPermissionKey = (typeof SYSTEM_PERMISSIONS)[number]["key"];

export type RoleSeed = {
  name: string;
  slug: string;
  description: string;
  isSystem: boolean;
  scope: PermissionScope;
  permissionKeys: string[] | "*";
};

export const SYSTEM_ROLES: RoleSeed[] = [
  {
    name: "Super Admin",
    slug: "super_admin",
    description: "Platform operator with full access across all modules",
    isSystem: true,
    scope: "global",
    permissionKeys: "*",
  },
  {
    name: "HR Manager",
    slug: "hr_manager",
    description: "Employee management, attendance, leave, and documents",
    isSystem: true,
    scope: "company",
    permissionKeys: [
      "dashboard.view.read",
      "company.profile.read",
      "branch.profile.read",
      "branch.profile.manage",
      "department.profile.read",
      "department.profile.manage",
      "designation.profile.read",
      "designation.profile.manage",
      "employee.profile.read",
      "employee.profile.create",
      "employee.profile.update",
      "employee.profile.delete",
      "employee.profile.export",
      "employee.profile.import",
      "employee.salary.read",
      "employee.salary.update",
      "document.file.read",
      "document.file.create",
      "document.file.update",
      "document.file.delete",
      "attendance.record.read",
      "attendance.record.create",
      "attendance.record.update",
      "attendance.record.approve",
      "attendance.record.export",
      "gps_attendance.record.read",
      "gps_attendance.record.configure",
      "leave.view.read",
      "leave.apply.create",
      "leave.approve.approve",
      "leave.reject.reject",
      "leave.cancel.delete",
      "leave.module.manage",
      "leave.policy.manage",
      "leave.balance.manage",
      "leave.request.read",
      "leave.request.approve",
      "leave.request.reject",
      "holiday.calendar.read",
      "holiday.calendar.manage",
      "shift.schedule.read",
      "shift.schedule.manage",
      "report.general.read",
      "report.attendance.read",
      "audit.log.read",
    ],
  },
  {
    name: "Accounts Manager",
    slug: "accounts_manager",
    description: "Payroll, salary structures, loans, advances, and financial reports",
    isSystem: true,
    scope: "company",
    permissionKeys: [
      "dashboard.view.read",
      "employee.profile.read",
      "employee.salary.read",
      "payroll.payrun.read",
      "payroll.payrun.create",
      "payroll.payrun.approve",
      "payroll.payrun.export",
      "payroll.view.read",
      "payroll.generate.create",
      "payroll.calculate.create",
      "payroll.approve.approve",
      "payroll.lock.manage",
      "payroll.unlock.override",
      "payroll.delete.delete",
      "payroll.payslip.read",
      "payroll.payslip.export",
      "payslip.view.read",
      "payslip.generate.create",
      "payslip.download.read",
      "payslip.email.manage",
      "salary_certificate.generate.create",
      "payroll_export.generate.create",
      "payroll.report.view",
      "payroll.report.export",
      "bank_transfer.generate.create",
      "bank_transfer.approve.approve",
      "accounting.export.create",
      "analytics.view.read",
      "cost_center.manage.manage",
      "payroll.rollback.manage",
      "payroll.retro.manage",
      "payroll.arrear.manage",
      "payroll.year.close",
      "payroll.backup.manage",
      "salary.view.read",
      "salary.create.create",
      "salary.update.update",
      "salary.delete.delete",
      "salary.assign.assign",
      "salary.approve.approve",
      "salary.structure.read",
      "salary.structure.create",
      "salary.structure.update",
      "salary.structure.approve",
      "loan.request.read",
      "loan.request.approve",
      "loan.request.manage",
      "loan.view.read",
      "loan.create.create",
      "loan.update.update",
      "loan.approve.approve",
      "loan.reject.reject",
      "loan.recover.manage",
      "loan.foreclose.manage",
      "advance.request.read",
      "advance.request.approve",
      "advance.manage.manage",
      "report.general.read",
      "report.general.export",
      "report.payroll.read",
      "report.payroll.export",
      "statutory.module.read",
      "statutory.module.manage",
      "statutory.pf.manage",
      "statutory.esi.manage",
      "statutory.pt.manage",
      "statutory.tds.manage",
      "overtime.module.read",
      "overtime.module.manage",
      "overtime.request.approve",
      "bonus.module.manage",
      "incentive.module.manage",
      "commission.module.manage",
      "allowance.module.manage",
      "expense.claim.read",
      "expense.claim.approve",
      "expense.claim.export",
    ],
  },
  {
    name: "Branch Manager",
    slug: "branch_manager",
    description: "Branch-scoped employee, attendance, and leave management",
    isSystem: true,
    scope: "branch",
    permissionKeys: [
      "dashboard.view.read",
      "employee.profile.read",
      "attendance.record.read",
      "attendance.record.approve",
      "leave.view.read",
      "leave.approve.approve",
      "leave.reject.reject",
      "leave.request.read",
      "leave.request.approve",
      "leave.request.reject",
      "report.attendance.read",
    ],
  },
  {
    name: "Employee",
    slug: "employee",
    description: "Self-service access to own profile, attendance, leave, and payslip",
    isSystem: true,
    scope: "self",
    permissionKeys: [
      "dashboard.view.read",
      "employee.profile.read",
      "document.file.read",
      "attendance.record.read",
      "leave.view.read",
      "leave.apply.create",
      "leave.request.read",
      "leave.request.create",
      "payroll.payslip.read",
      "payslip.view.read",
      "payslip.download.read",
      "expense.claim.read",
      "expense.claim.create",
      "training.program.read",
      "performance.review.read",
    ],
  },
];
